### ISSUE TITLE
Does not work on Win 10 19045

### ISSUE THREAD

**Issue by Guerra24** [ahmed605/10Mica#2]
Hello!

It works just fine on 22621, but I can't get it to work on 19045, it throws the following exceptions:

If declared in XAML
```cs
Exception thrown: 'Windows.UI.Xaml.Markup.XamlParseException' in LRReader.UWP.exe
An exception of type 'Windows.UI.Xaml.Markup.XamlParseException' occurred in LRReader.UWP.exe but was not handled in user code
The text associated with this error code could not be found.

Cannot create instance of type 'TenMica.TenMicaBrush' [Line: 12 Position: 64]

The program '[236] LRReader.UWP.exe' has exited with code 4294967295 (0xffffffff).
```

And if instantiated through code
```cs
Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
```

You can find the project src [here](https://github.com/Guerra24/LRReader/tree/develop/LRReader.UWP), if that is of any help. I'm trying to add it [here](https://github.com/Guerra24/LRReader/blob/develop/LRReader.UWP/Views/Root.xaml).

**Comment by ahmed605** [comment]
Hmm looks like the winmd isn't getting registered, I assume this is a nuget misconfiguration but not a problem in the library itself, will investigate the problem

**Comment by ahmed605** [comment]
I just tried it on both a managed project and a native project and it works for both, are you sure that you are using version `1.0.0-beta` (not `alpha`) and **not** using `AnyCPU`?

Also how are you trying it on 19045? via remote debugging or via a Release package?

**Comment by Guerra24** [comment]
I'm sure it is `1.0.0-beta` and not using `AnyCPU`.

Remote debugging on a VM, which so far has worked fine.

**Comment by ahmed605** [comment]
Hmm, can you check if `TenMica.dll` and `TenMica.winmd` are copied to the package root on the VM?
And if possible can you show me the generated `AppxManifest.xml` from the VM?

**Comment by Guerra24** [comment]
Sure!
![image](https://github.com/ahmed605/10Mica/assets/9023392/065d5eae-1a6c-4773-b832-9c3e3ee0cd53)
[AppxManifest.xml.txt](https://github.com/ahmed605/10Mica/files/12730868/AppxManifest.xml.txt)

**Comment by ahmed605** [comment]
That's so weird, it's registered
```xml
<Extension Category="windows.activatableClass.inProcessServer">
  <InProcessServer>
    <Path>TenMica.dll</Path>
    <ActivatableClass ActivatableClassId="TenMica.TenMicaBrush" ThreadingModel="both" />
  </InProcessServer>
</Extension>
```

**Comment by ahmed605** [comment]
I have tried using a Release package only, I will try again using remote debugging on a VM to see if I can reproduce the issue

**Comment by ahmed605** [comment]
I just tried using remote debugger and it still works
![tenmica](https://github.com/ahmed605/10Mica/assets/34550324/d25dc8ab-daa9-42ce-9454-db5623fb0ce9)

**Comment by ahmed605** [comment]
did you use any kind of debloaters on the VM? and did you try with an actual device, maybe the problem is in the VM

**Comment by Guerra24** [comment]
No, and I don't have any devices with Win 10 😅 just set up the vm for this... I will try on a new VM with multiple builds just in case, I'll let you know, thanks for your time!

**Comment by ahmed605** [comment]
no worries, let me know the results!
BTW this is unrelated to this bug but in order for Mica to render under VMs you have to apply this Registry value
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm]
"ForceEffectMode"=dword:00000002
```
This won't fix the exception tho, this is just for it to render correctly after fixing the exception.

I would also recommend HyperV for the VM, it has a really good Windows integration.

**Comment by Guerra24** [comment]
Well, figured out the issue. Turns out that on 19041-5 the manifest sometimes is not re-registered. Once I uninstall the app and redeploy it, it works just fine without issues. My guess is that this issue only happens when remote debugging, but I have not tested it with VS on the VM itself.

Windows being windows as always 🙃

Going to close the issue, thanks again!
